---
- friendly_name: "New Super Mario Bros. Wii (PAL)"
  short_name: 'n'
  include_dirs: ['include', 'src']
  multi_build: {
    pal: 'kamek_pal.x',
  }
  dynamic_link: true
  
- friendly_name: "New Super Mario Bros. Wii (PALV2)"
  short_name: 'n'
  include_dirs: ['include', 'src']
  multi_build: {
    pal2: 'kamek_pal2.x',
  }
  dynamic_link: true
  
- friendly_name: "New Super Mario Bros. Wii (NTSC)"
  short_name: 'n'
  include_dirs: ['include', 'src']
  multi_build: {
    ntsc: 'kamek_ntsc.x',
  }
  dynamic_link: true
  
- friendly_name: "New Super Mario Bros. Wii (NTSCV2)"
  short_name: 'n'
  include_dirs: ['include', 'src']
  multi_build: {
    ntsc2: 'kamek_ntsc2.x',
  }
  dynamic_link: true
  
- friendly_name: "New Super Mario Bros. Wii (JPN)"
  short_name: 'n'
  include_dirs: ['include', 'src']
  multi_build: {
    jpn: 'kamek_jpn.x',
  }
  dynamic_link: true
  
- friendly_name: "New Super Mario Bros. Wii (JPNV2)"
  short_name: 'n'
  include_dirs: ['include', 'src']
  multi_build: {
    jpn2: 'kamek_jpn2.x',
  }
  dynamic_link: true

- friendly_name: "New Super Mario Bros. Wii (KOR)"
  short_name: 'n'
  include_dirs: ['include', 'src']
  defines: {'REGION_K'}
  multi_build: {
    kor: 'kamek_kor.x',
  }
  dynamic_link: true

- friendly_name: "New Super Mario Bros. Wii (TWN)"
  short_name: 'n'
  include_dirs: ['include', 'src']
  defines: {'REGION_W'}
  multi_build: {
    twn: 'kamek_twn.x'
  }
  dynamic_link: true
#  rel_area_start: 0x807684C0
#  rel_area_end: 0x80B75CA8
  
